default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: abcd1234
  host: localhost

development:
  <<: *default
  database: db/quill_quest

test:
  <<: *default
  database: db/quill_quest_test

production:
  <<: *default
  database: quill_quest
  username: postgres
  password: abcd1234
  host: localhost
